--[[

***************************************************************    
*** NOTICE TO TRANSLATORS: DO NOT EDIT THIS FILE DIRECTLY! ***

We have provided a standard PO file to translation in /scripts/languages/strings.po
To add a new language:
- User a PO editor such as POEdit (http://www.poedit.net/) to translate strings.po
- Load your own PO file under /scripts/languages/language.lua

***************************************************************
]]

local STRINGS=
{
	APPNAME = "Invisible, Inc.",

	MISSIONS = 
	{
		NULL = {},
		JAILBREAK = include( "mission_strings/jailbreak_strings" ), 
		DATA_DISK = include( "mission_strings/data_disk_strings" ), 
		HOSTAGE = include( "mission_strings/hostage_strings" ),
		UPLOAD = include( "mission_strings/upload_strings" ),
		INTERROGATE = include( "mission_strings/interrogate_strings" ),
		NEUTRALIZE = include( "mission_strings/neutralize_strings" ),
		SABOTAGE = include( "mission_strings/sabotage_strings" ),

		ESCAPE = include( "mission_strings/escape_strings" ),

		UTIL = {
			SERVER_FARM = "伺服器中心",
			PROGRAM_UPGRADES_AVAILABLE = "有可升級的INCOGNITA軟體",
			ENCRYPTED_DATA = "偵測到加密資料",
			ADVANCED_TECHNOLOGY = "偵測到高級科技物",			
			HEAT_SIGNATURE_DETECTED  =  "偵測到熱源",
			RESCUE_PRISONER = "拯救囚犯"
		},	


		LOCATIONS = 
		{
			TUTORIAL = {
				NAME = "Interrogation Room",
			},

			DETENTION_CENTER = {
				NAME = "Detention Center",
				INSET_TITLE = "CORPORATE PRISONERS",
				INSET_TXT = "Corporate Detention Centers hold previously captured agents as well as wealthy collaterals.\n\nThis could be profitable.",
			},

			SERVER_FARM = {
				NAME = "Server Farm",
				INSET_TITLE = "MAINFRAME SOFTWARE",
				INSET_TXT = "Server Farms are where they develop new firewall technology.\n\nBreak in, and Incognita can re-purpose them for her own use.",			
			},

			SECURITY = {
				NAME = "Secure Holding Facility",
				INSET_TITLE = "CORPORATE ESPIONAGE",
				INSET_TXT = "Holding facilities contain valuable assets.",
			},

			GUARD_OFFICE = {
				NAME = "Security Dispatch",
				INSET_TITLE = "ADVANCED GEAR",
				INSET_TXT = "Heads of security sometimes acquire top of the line or experimental items from R&D.\n\nFinding one of these trophies can give the right agent a considerable edge.",
			},

			TERMINALS = {
				NAME= "Executive Terminals",
				INSET_TITLE = "CURRENT SITE PLANS",
				INSET_TXT = "These locations hold information about current and future sites of high value locations.\n\nWe should go here to find more points of attack.",						
			},

			NANO_FAB = {
				NAME = "Nanofab Vestibule",
				INSET_TITLE = "CONTRABAND TEMPLATES",
				INSET_TXT = "While we can re-purpose Nanofabs anywhere, the contraband Nanofab Vestibules that the corporations manufacture have far more stock.\n\nGo here to replenish our supplies.",				
			},
			VAULT = {
				NAME = "Vault",
				INSET_TITLE = "CREDIT RESERVES",
				INSET_TXT = "Executives love their offshore accounts, and so do we. \n\nInfiltrate these locations for maximum credit advantage.",				
			},			



			TREASURY_HOLDING = "Treasury Office",
		},
	},

	CENTRAL_BARKS = 
	{
		AGENT_DOWN = "Agent down. This is going sideways.",
		TEAM_DOWN = "We've lost contact with the team. Bloody hell!",
	},


	GUARD_STATUS = 
	{
		STATUS = "狀態:",
		PATROLLING = "巡邏中",
		IDLE = "定點警戒",
		INVESTIGATING = "調查中",
		HUNTING = "獵捕中",
		COMBAT = "警戒",
	},

	PROGRAMS = 
	{
		POWER_PER_TURN = "%d PWR / TURN",
		POWER = "%d PWR",
		COST = "COST: <c:8fffff>%d PWR</>",
		COST_PER_TURN = "COST: <c:8fffff>%d PWR PER TURN</>",
		EQUIPPED = "EQUIPPED",
		PURCHASED = "P R O G R A M  P U R C H A S E D",
		PURCHASED_DESC = "You've purchased a program to be used by Incognita:\n%s",

		POWER_DRIP = 
		{
			NAME = "POWER DRIP",
			DESC = "Generate 1 PWR point per turn",
			SHORT_DESC = "PASSIVE",
			HUD_DESC = "+1 PWR PER TURN",
			WARNING = "POWER DRIP\n+ 1 PWR",
			MODAL_1 = "I N C O G N I T A  I S  R U N N I N G  A  P R O G R A M",
			MODAL_2 = "POWER DRIP",
			MODAL_3 = "Your agency has provided the Power Drip program for you. This program automatically generates 1 PWR at the start of each turn.",
		},

		LOCKPICK =
		{
			NAME = "LOCKPICK 1.0",
			DESC = "Breaks 1 firewall for 2 PWR.",
			SHORT_DESC = "USE LOCKPICK",
			HUD_DESC = "BREAKS 1 FIREWALL",
		},

		WRENCH_2 =
		{
			NAME = "WRENCH 2",
			DESC = "Only breaks firewalls exactly equal to 2 strength",
			SHORT_DESC = "USE WRENCH",		
			HUD_DESC = "BREAKS EXACTLY 2 FIREWALLS",
		},

		WRENCH_3 =
		{
			NAME = "WRENCH 3",
			DESC = "Only breaks firewalls exactly equal to 3 strength",
			SHORT_DESC = "USE WRENCH",		
			HUD_DESC = "BREAKS EXACTLY 3 FIREWALLS",
		},

		WRENCH_4 =
		{
			NAME = "WRENCH 4",
			DESC = "Only breaks firewalls exactly equal to 4 strength",
			SHORT_DESC = "USE WRENCH",		
			HUD_DESC = "BREAKS EXACTLY 4 FIREWALLS",
		},

		WRENCH_5 =
		{
			NAME = "WRENCH 5",
			DESC = "Only breaks firewalls exactly equal to 5 strength",
			SHORT_DESC = "USE WRENCH",		
			HUD_DESC = "BREAKS EXACTLY 5 FIREWALLS",
		},

		HAMMER = 
		{
			NAME = "HAMMER",
			DESC = "Breaks 5 firewalls for 5 PWR.",
			SHORT_DESC = "USE HAMMER",		
			HUD_DESC = "BREAKS 5 FIREWALLS",
		},

		DAGGER = 
		{
			NAME = "DAGGER",
			DESC = "Breaks 3 firewalls. 5 turn cooldown.",
			SHORT_DESC = "USE DAGGER",
			HUD_DESC = "BREAKS 3 FIREWALLS",
		},

		PARASITE = 
		{
			NAME = "PARASITE",
			DESC = "Infect target to break 1 firewall at the start of your turn.",
			SHORT_DESC = "HOST PARASITE",		
			HUD_DESC = "BREAKS 1 FIREWALL PER TURN",
			ALREADY_HOSTED = "ALREADY HAS PARASITE",
		},

		SNIFFER =
		{
			NAME = "DAEMON SNIFFER",
			DESC = "Reveals hidden Daemons when used.",
			SHORT_DESC = "REVEAL DAEMON",
			HUD_DESC = "REVEALS DAEMON",
		},

		HUNTER =
		{
			NAME = "HUNTER",
			DESC = "Kills Daemons for 5 PWR. 3 turn cooldown",
			SHORT_DESC = "USE HUNTER",
			HUD_DESC = "KILL DAEMON",
		},

		PING =
		{
			NAME = "PING",
			DESC = "Create a distraction noise",
			SHORT_DESC = "MAKE NOISE",			
			HUD_DESC = "CREATES NOISE DISTRACTION",
		},

		ORACLE =
		{
			NAME = "ORACLE",
			DESC = "Take over a random camera on the level",
			SHORT_DESC = "TAKE RANDOM CAMERA",	
			HUD_DESC = "CONTROL A RANDOM CAMERA",
		},

		FUSION =
		{
			NAME = "FUSION",
			DESC = "Gain 3 PWR each turn while on cooldown. 4 turn cooldown.",
			SHORT_DESC = "GAIN PWR ON COOLDOWN",	
			HUD_DESC = "GAIN 3 PWR EACH TURN WHILE ON COOLDOWN",
			WARNING = "FUSION\n+ 3 PWR",
		},

		WINGS =
		{
			NAME = "WINGS",
			DESC = "Increases AP of all agents by 1",
			SHORT_DESC = "TOGGLE: INCREASE AP",
			HUD_DESC = "+1 AP ON ALL AGENTS",
		},

		SHADE =
		{
			NAME = "SHADE",
			DESC = "Reduces sight range of guards",
			SHORT_DESC = "TOGGLE: REDUCE SIGHT",
			HUD_DESC = "REDUCE GUARD SIGHT",
		},


	},

	DAEMONS = 
	{
		DAEMON_PNL_TITLE = "T H E  C O R P O R A T I O N  I S  I N S T A L L I N G:",
		WARNING_TITLE = "%s Daemon",
		GENERIC_TITLE = "Installing Daemon",
		RUBIKS = 
		{
			NAME = "RUBIKS",
			DESC = "Raises FIREWALLS",
			SHORT_DESC = "Raises FIREWALLS by one",
			ACTIVE_DESC = "ALL FIREWALLS RAISED BY DAEMON",
		},
		VALIDATE = 
		{
			NAME = "VALIDATE",
			DESC = "Brings an additional guard onto the level",
			SHORT_DESC = "Spawns guard",
			ACTIVE_DESC = "GUARD SPAWNED BY DAEMON",
		},
		SIPHON = 
		{
			NAME = "SIPHON",
			DESC = "Drains PWR",
			SHORT_DESC = "Drains PWR",
			ACTIVE_DESC = "%d PWR DRAINED BY DAEMON",
		},
		FRACTAL = 
		{
			NAME = "FRACTAL",
			DESC = "Creates two new DAEMON programs on random objects",
			SHORT_DESC = "Spawns additional Daemons",
			ACTIVE_DESC = "NEW DAEMONS INSTALLED BY DAEMON",
		},
		PARADOX = 
		{
			NAME = "PARADOX",
			DESC = "Stops INCOGNITA from hacking temporarily",
			SHORT_DESC = "Disables hacking ability",
			ACTIVE_DESC = "Incognita hacking ability stopped for %d turns",
		},
		BLOWFISH = 
		{
			NAME = "BLOWFISH",
			DESC = "Advances tracker",
			SHORT_DESC = "Advances tracker",
			ACTIVE_DESC = "ALARM RAISED %d BY DAEMON",
		},		
		LABYRINTH = 
		{
			NAME = "LABYRINTH",
			DESC = "Reduces all agent 1 AP",
			SHORT_DESC = "Reduces agents 1 AP",
			ACTIVE_DESC = "DAEMON REDUCES AGENTS AP BY %d",
		},		
		
	},


	UI =
	{
		EARLY_ACCESS_MESSAGE = "Invisible Inc. is a deep, procedural stealth game. It requires you to think about every move lest it be your last.\n\nThis game is still in development, and we will be updating the game regularly. If you have questions or comments, please stop by our forums!",
		EARLY_ACCESS_NEXT_UPDATE = "STATUS: %s",
		EARLY_ACCESS_FRESH = "<c:8cffff>FRESH BUILD!</>",
		EARLY_ACCESS_DAYS = "<c:8cffff>NEXT BUILD IN %d DAYS</>",
		EARLY_ACCESS_IMMINENT = "<c:8cffff>NEXT BUILD IMMINENT</>",

		DIFFICULTY = 
		{
			"守備中",
			"仔細守備中",
			"非常仔細守備中",
			"超級仔細守備中",
		},

		NORMAL_DIFFICULTY = "Easy", 
		HARD_DIFFICULTY = "Normal", 
		DIFFICULTY_STR = "Difficulty",

		NORMAL_DIFFICULTY_TOOLTIP = "- Neural Disrupters KO for longer.\n- Firewalls are weaker.\n- Alarm stages are less dangerous.\n- Safes, objectives and guards have more credits.",
		HARD_DIFFICULTY_TOOLTIP = "- Neural Disrupters have shorter KO.\n- Firewalls are stronger.\n- Alarm stages are more dangerous.\n- Safes, objectives and guards have fewer credits.",

		QUIT_CONFIRM = "Are you sure you want to exit the game?",
		QUIT = "Exit Game",

		CAUGHT_MODAL_1 = "C A U G H T  B Y  A  G U A R D",
		CAUGHT_MODAL_2 = "GUARD OVERWATCH",
		CAUGHT_MODAL_3 = "A guard is about to shoot your agent. Your agent can quickly hide behind any cover within one square, or you can send another agent to give support.",

		CENTRAL_MISSION_DIFFICULTY = "Looks like the corporations are getting nervous.\n\nThey've updated their security on existing locations. We've also located additional points of interest.",

		ALARM_INSTALL ="T H E  C O R P O R A T I O N  I N C R E A S E S  S E C U R I T Y",

		ALARM_INSTALL_FIRST_1 ="ALARM SYSTEM",
		ALARM_INSTALL_FIRST_2 ="The Corporation has detected Incognita synchronizing with your agents. Their automated system is hacking through Incognita's encryption and assessing the threat.\n\nThe longer you stay here, the more security it's going to send to stop you, so time is of the essence.",

		ALARM_LEVEL_NUM = "ALARM LEVEL %d",

		ALARM_FIREWALLS = "The corporation has installed firewall upgrades. All firewalls have increased in strength by +%d",
		ALARM_CAMERAS = "The corporation is activating additional cameras. You have one turn before they are fully activated.",
		ALARM_PATROLS = "The corporation has brought %d more guard patrol(s) into the building.",
		ALARM_BOOTING = "They've cracked Incognita first layer of encryption. Be careful, the next alarm levels will be quite dangerous.",
		ALARM_ENFORCERS = "The corporation has called in %d elite enforcer(s). Be careful: they are fast and dangerous.",

		SCANNER_ALERT_HEAD = "A D V A N C E D  C O R P O R A T E  E Q U I P M E N T",
		SCANNER_ALERT_TITLE = "SCANNING AMP",
		SCANNER_ALERT_TXT = "An advanced scanning amplifier has pinpointed your location. A guard has been sent to investigate.",

		PWR_DRAIN_ALERT_HEAD = "A D V A N C E D  C O R P O R A T E  E Q U I P M E N T",
		PWR_DRAIN_ALERT_TITLE = "POWER REVERSAL NODE",
		PWR_DRAIN_ALERT_TXT = "A high powered magnetic device is draining your PWR. It will drain %d PWR per turn",

		STATDISPLAY = "CURRENT HIGH SCORE: %d\nCURRENT XP: %d",
		SAVE_NOT_COMPATIBLE = "Save game not compatible",
		SAVE_GAME_VERSION = "Save game version:",
		CURRENT_VERSION = "Current version:",
		CONTINUE_CAMPAIGN = "Continue campaign",

		UPDATE_COMPLETE = "NO REMAINING DATA\n--- DECODE COMPLETE ---",

		START_MISSION = "> START MISSION",

		MISSION_COMPLETE = "MISSION REPORT",
		CAMPAIGN_COMPLETE = "STORY MODE COMPLETE",
		CAMPAIGN_COMPLETE_DESC = "You've completed the Early Access Story Mode of Invisible, Inc. This game is still in development, and we will be regularly adding new content to the game.\n\nWe'd love to hear about your experiences with the Story Mode! If you'd like to share your thoughts, please visit us in our forums.\n\nThank you for supporting the game!",
		ENDLESS_MODE_UNLOCKED = "ENDLESS MODE UNLOCKED",
		ENDLESS_MODE_DESC = "You've unlocked Endless Mode! Start a new game to access it.",
		NEXT_MISSION = "> NEXT MISSION",
		UPGRADE = "> UPGRADE AGENTS",
		MAP = "> MISSION SELECTION",

		ABORT_MISSION = "ABORT MISSION",
		RETIRE_AGENCY = "RETIRE AGENCY",
		SAVE_AND_EXIT = "SAVE AND EXIT",
		EXIT = "X LOG OUT",
		RETRY = "> RETRY",
		CONTINUE = "> CONTINUE",
		FORUMS = "VISIT FORUMS",
		BACK = "BACK",

		ACTIVE = "ACTIVE",
		REEQUIPPED = "RE-EQUIPPED",
		MIA = "MIA",
		NOT_PAID = "NOT_PAID",

		LOCKED = "LOCKED",

		MAP_EXPLORATION = "MAP EXPLORATION",
		EXPLORATION_CREDITS = "EXPLORATION BONUS",
		MISSION_REWARD = "CLIENT INVOICE",
		CLEAN_SWEEP = "CLEAN SWEEP BONUS",
		CLEAN_UP_COST = "CLEAN UP COST",
		ALARM_LEVEL = "ALARM TRACKER LEVEL",
		KILLS = "GUARDS NEUTRALIZED",
		NO_BONUS = "NO BONUS",
		TOTAL_CREDITS ="NEW CREDIT TOTAL",
		CURRENT_CREDITS ="CURRENT CREDITS",
		CORPORATE_INTEL ="CORPORATE INTELLIGENCE",
		AGENTS_LOST ="AGENTS LOST",
		TEAM_ELIMINATED = "TEAM ELIMINATED",
		CORPORATE_MAP = "CORPORATE MAP",
		AGENTS_HIRED = "AGENTS HIRED",
		ITEM_ACQUIRED = "I T E M  A C Q U I R E D",

		SECURITY_HACKED = "SECURITY HACKED", 
		GUARDS_KOD = "GUARDS KO'D",
		SAFES_LOOTED = "SAFES LOOTED", 
		CREDITS_EARNED = "CREDITS EARNED", 
		PROGRAMS_EARNED = "PROGRAMS EARNED",
		ITEMS_EARNED = "ITEMS EARNED", 
		PROGRAMS_ACQUIRED = "PROGRAMS ACQUIRED",
		ITEMS_PURCHASED = "ITEMS PURCHASED",
		MISSIONS_COMPLETED = "MISSIONS COMPLETED", 
		TOTAL_XP = "TOTAL EXPERIENCE EARNED", 

		UPGRADE_SCREEN_AVAILABLE_CREDITS = "%d",
		UPGRADE_SCREEN_SELECT_UPGRADE = "SELECT UPGRADE",
		UPGRADE_SCREEN_UPGRADE_TITLE = "%s UPGRADE",
		UPGRADE_SCREEN_AGENT_DESC_NAME = "NAME: %s",
		UPGRADE_SCREEN_AGENT_DESC_AGE = "AGE: %d",

		TEMP_FINAL_MISSION_TITLE = "FINAL MISSION",
		TEMP_FINAL_MISSION_DESC = "This distress mission is a temporary final mission that we've implemented for Early Access. The final game will have these distress missions through the campaign, and present you with one final, extremely challenging mission.\n\nAre you ready to take on this final challenge?",

		NEW_GAME_CONFIRM = "> I'M READY",

		TOOLTIP_REQUIRES_SKILL_LVL = "Requires %s Skill Level %d",
		TOOLTIP_CANT_PURCHASE = "You can't purchase right now.",
		TOOLTIP_ALREADY_OWN = "You already own this mainframe program!",
		TOOLTIP_PROGRAMS_FULL = "You already have maximum mainframe programs!",
		TOOLTIP_INVENTORY_FULL = "Unit's inventory is full!",
		TOOLTIP_NOT_ENOUGH_CREDIT = "Insufficient funds!",
		TOOLTIP_LEAVING_ITEM_SCREEN = "Are you sure you want to leave without taking these items?",
		TOOLTIP_LEAVING_ITEM_SCREEN_YES = "Leave",

		TOOLTIP_AGENT_DOWN = "AGENT DOWN",
		TOOLTIP_AGENT_DOWN_DESC = "This agent is down. Use a medgel to revive.",
		TOOLTIP_NAME_PARALYZED = "%s, PARALYZED",
		TOOLTIP_NAME_KO_TIME = "%s, KO (%d)",
		TOOLTIP_TAGGED = "TAGGED",
		TOOLTIP_TAGGED_DESC = "",


		TOOLTIP_HACK_WITH_INCOGNITA = "HACK WITH INCOGNITA",
		TOOLTIP_HACK_CAMERA_DB = "Reveals the location of all cameras",
		TOOLTIP_HACK_CONSOLE_DB = "Reveals the location of all consoles",
		TOOLTIP_HACK_GUARD_DB = "Reveals the location of all heart monitors",
		TOOLTIP_HACK_MAP_DB = "Reveals the outline of the facility",

		SHOP_INVENTORY = "INVENTORY",
		SHOP_LOOT ="LOOT %s_",
		SHOP_SELL = "INVENTORY / SELL",
		SHOP_SERVER = "SERVER FARM",
		SHOP_PRINTER = "NANO FABRICATOR",
		SHOP_CANNOT_SELL = "CAN'T SELL",

		HUD_DAYS_TURN_ALARM = "DAY %02d  /  HOUR %02d  /  %s  /  %s  /  FAST MODE",
		HUD_ATTACK_USED = "ATTACK USED",

		HUD_CONFIRM_ABILITY = "CONFIRM ACTION",
		HUD_CONFIRM_ESCAPE = "The level will end if %s escapes. Are you sure you want to leave %s behind?",

		MAP_SCREEN_DAYS_SPENT = "DAY %02d / %02d:%02d:%02d",
		MAP_SCREEN_REMAINING = "<c:F4FF78>%s</> HOURS REMAINING",
		MAP_SCREEN_EXPIRES = "EXPIRES:  <c:F4FF78>%s HOURS</>",
		MAP_SCREEN_DISTRESS = "DISTRESS SIGNAL",
		MAP_SCREEN_LOCATION = "LOCATION",
		MAP_SCREEN_TRAVEL_TIME = "Travel Time: %d hours",
		MAP_DIALOG_1 = "Welcome back, Operator. The corporations are getting stronger by the day, so we need to choose our locations carefully.\n\nSelect your next target.",
		MAP_DIALOG_INFINITE_INTRO = 
		{
			"Welcome back, Operator. There's plenty of profit to be made out there if we're bold enough.\n\nI'm authorizing you to go off-contract.",
			"Incognita is looking for corporate vulnerabilities. Exploit these, take whatever you can, and rebuild the firm.",
			"This company is my life's work. We've all bled for this.\n\nDon't disappoint me, Operator.",
		},

		MAP_DIALOG_STORY_INTRO = 
		{
			"Welcome back, Operator.\n\nIncognita is picking up some strange patterns in the global market. We don't know what it all means yet, but it's accelerating.",
			"We should prepare for a major action in the coming days.",
			"This won't be easy - our resources are stretched thin. I've lined up some lucrative contracts and targets of opportunity that we can exploit to better our position.",
			"I'll let you choose the missions as you see fit. But be careful - we can't afford another setback right now."
		},

		MAP_CODE_NAME = "CODE NAME: ",
		MAP_SCREEN_EXPIRED = "CONTRACT EXPIRED",
		MAP_SCREEN_DAYS = "DAYS",

		MAP_INFILTRATE = "> INFILTRATE",

		BUTTON_ACCEPT = "ACCEPT",
		BUTTON_CANCEL = "CANCEL",
		BUTTON_APPLY = "APPLY",

		TEAM_SELECT = 
		{
			LOCKED_AGENT_NAME = "CLASSIFIED",
			UNLOCK_TO_USE = "REQUIRES MORE XP TO UNLOCK",
			LOCKED_AGENT_DESC = "THIS AGENT IS CLASSIFIED.",
			LOCKED_LOADOUT = "You've selected CLASSIFIED components to your team. Please select a team loadout that you have access to.",
		},

		SAVESLOTS =
		{
			DELETE_AREYOUSURE = "Are you sure you want to delete this save slot?",
			DELETE_SAVE = "Delete Save",
			SEE_PATCHNOTES = "READ MORE",
			CONTINUE = "CONTINUE GAME",
			ENDLESS_MODE = "Endless Mode",
			STORY_MODE = "Story Mode",
			TUTORIAL = "Tutorial",
			DAYS_SPENT = "%02d DAYS / %02d HOURS",
			EMPTY_SLOT = "> START NEW GAME",

			PLAYED_TUTORIAL = "It is recommended you play the tutorial the first time you play Invisible, Inc.\n\nDo you want to play the tutorial first?",
			PLAY_TUTORIAL = "PLAY TUTORIAL",
			PLAY_STORY = "SKIP TUTORIAL",
		},

		ACTIONS = 
		{
			LOOT_BODY = 
			{
				NAME = "STEAL",
				TOOLTIP = "Steal valuables",
			},
			SEARCH_SAFE = 
			{
				NAME = "Search Safe",
				TOOLTIP = "Unlock the safe to search its contents",
			},
		},


		REASON =
		{
			NOT_ENOUGH_PWR = "Not enough PWR",
			NOT_ENOUGH_CREDITS = "Not enough credits",
			INCOGNITA_LOCKED_DOWN = "Incognita locked down",
			EQUIPPED_ON_COOLDOWN = "Equipped ability on cooldown",
			NO_CAMERAS = "No remaining uncaptured cameras",
			ALREADY_USED = "Already used this turn",
		},		
	},

	CORP = 
	{
		FTM = 
		{
			NAME = "Factory to Market",
			LOCATIONS = 
			{
				PR_MEDIA_STUDIO = "FTM Propaganda Media Studio",
				CORP_LECTURE_HALL = "FTM Corporate Lecture Hall",
				INVENTORY_MANAGEMENT = "FTM Inventory Management Facility",
				SECURITY_HUB = "FTM Central Security Complex",
			},
			STREET_NAMES = 
			{
				"1ST DIVISION",
				"2ND DIVISION",
				"3RD DIVISION",
				"4RD DIVISION",
				"5TH DIVISION",
			},
			CITIES = 
			{
				"NORTH",
				"SOUTH",
				"EAST",
				"WEST",
			},
		},
		SANKAKU = 
		{
			NAME = "Sankaku",
			LOCATIONS = 
			{
				ROBOT_DESIGN_STUDIO = "Sankaku Robot Design Studio",
				TESTING_FACILITY = "Sankaku Testing Facility",
				REPAIR_MAINTENANCE  = "Sankaku Repair & Maintenance Facility",
				AI_SUPER_COMPUTER  = "Sankaku AI Super Computer",
			},
			STREET_NAMES = 
			{
				"1ST DIVISION",
				"2ND DIVISION",
				"3RD DIVISION",
				"4RD DIVISION",
				"5TH DIVISION",
			},
			CITIES = 
			{
				"SEIKAKU",
				"SENNIN",
				"KOKURO",
			},
			THREATS = 
			{
				GRID = 
				{
					NAME = "The Keibi Grid",
					DESC = "Expect a larger number DAEMON programs.\n\nThese programs may also be more deadly that usual."
				},
				AKUMA = 
				{
					NAME = "AKUMA Program",
					DESC = "Extremely armored.\n\nDense Firewall protection."
				},
				GRID = 
				{
					NAME = "NULL Drone",
					DESC = "Creates a dead zone in the mainframe.\n\nINCOGNITA cannot hack anything in this zone."
				},
			}
		},
		KO = 
		{
			NAME = "Kelfried & Oden",
			LOCATIONS = 
			{
				INTERROGATION_ROOM = "K&O Interrogation Room",
				SUPER_SOLDIER = "K&O Super Soldier Steroid Lab",
				WEAPONS_LAB  = "K&O Weapons Lab",
				PRACTICE_AREA  = "K&O Practice Area",
				SOLITARY_CONFINEMENT  = "K&O Solitary Confinement Facility",
			},
			STREET_NAMES = 
			{
				"1ST DIVISION",
				"2ND DIVISION",
				"3RD DIVISION",
				"4RD DIVISION",
				"5TH DIVISION",
			},
			CITIES = 
			{
				"NORTH",
				"SOUTH",
				"EAST",
				"WEST",
			},
			THREATS = 
			{
				THOR = 
				{
					NAME = "THOR Division",
					DESC = "Heavily armored.\n\nExtra resistant to KO.\n\nVulnerable to rear attacks."
				},
				TURRET = 
				{
					NAME = "LOKI Turret Network",
					DESC = "Staionary defense turrets\n\nPowered by local generators."
				},
				SCANNING = 
				{
					NAME = "TYR Scanning Suite",
					DESC = "A static array of sensors and scanning equipment.\n\nDoubles building scanning speed while active."
				},
				SPECIALOPS = 
				{
					NAME = "Special Ops Team",
					DESC = "Wide range of view.\n\nWill spot hidden units."
				},
			}

		},
		PLASTECH = 
		{
			NAME = "Plastech",
			LOCATIONS = 
			{
				RE_EDUCATION_LAB = "Plastech Re-education Lab",
				SURGICAL_LAB = "Plastech Surgical Lab",
				FAILED_EXPERIMENT  = "Plastech Failed Experiment Storage",
				OBSERVATION_CHAMBER  = "Plastech Observation Chamber",
			},
			STREET_NAMES = 
			{
				"1ST DIVISION",
				"2ND DIVISION",
				"3RD DIVISION",
				"4RD DIVISION",
				"5TH DIVISION",
			},
			CITIES = 
			{
				"NORTH",
				"SOUTH",
				"EAST",
				"WEST",
			},
			THREATS = 
			{
				PSI = 
				{
					NAME = "Psi Corp",
					DESC = "Psionicly scans for intruders.\n\nWill mentally link to targets scanned or seen.\n\nLinked targets will suffer various effects until the link is broken."
				},
				GHOST = 
				{
					NAME = "Ghost Division",
					DESC = "Invisible melee assassins.\n\nCloaking field is detectable at short range."
				},
			}

		},
	},


	ITEMS = {
		AMMO = "AMMO %d/%d",

		TOOLTIPS = {
			AIM ="AIM",
			AIM_DESC = "Click this weapon to aim and shoot at an enemy.",
			ARMOR_PIERCING = "Armor Piercing",
			ARMOR_PIERCING_DESC = "Armor Piercing %d",
			KO_DAMAGE = "KO Damage",
			KO_DAMAGE_DESC = "Knocks a guard out for %d turns",
			RECHARGE =  "Recharge",
			RECHARGE_DESC = "%d turn cooldown",
			COSTPOWER = "Use PWR",
			COSTPOWER_DESC = "Consumes %d PWR when used",
			
			CANTAG = "Tags a target",
			CANTAG_DESC = "Tagged targets reveal their patrol paths",			
		},

		KEYWORDS = {
			CRITICAL = "This effect triggers after the agent successfully makes a critical hit.",
			NETWORK = "This effect triggers after any Incognita has broken all the ICE on any firewall.",
			MELEE = "This effect triggers after this agent successfully knocks out an enemy with a melee attack.",
			CLOAK = "This effect triggers after the agent becomes cloaked for any reason.",
			ITEM = "This effect triggers when the agent uses an inventory item.",	
		},

		AUGMENT = "AUGMENT",

		AUGMENTS = {
			SADOCHISTIC_PUMPS = "Sadochistic Pumps",
			SADOCHISTIC_PUMPS_TIP = "Killing adds 3 AP",

			NET_DOWNLINK = "Net Downlink",
			NET_DOWNLINK_TIP ="Agent gains 2 AP",

			ANATOMY_ANALYSIS = "Anatomy Analysis",
			ANATOMY_ANALYSIS_TIP = "Kills ignore guard heart monitors and do not raise the tracker.",

			DISTRIBUTED_PROCESSING = "Distributed Processing",
			DISTRIBUTED_PROCESSING_TIP = "50% chance to gain a PWR point at the beginning of each turn.",

			TORQUE_INJECTORS = "Torque Injectors",
			TORQUE_INJECTORS_TIP = "Gain 3 AP",

			TITANIUM_RODS = "Titanium Rods",
			TITANIUM_RODS_TIP = "Deal 1 extra KO damage",

			HOLOCIRCUIT = "HoloCircuit Overloaders",
			HOLOCIRCUIT_TIP ="Knock out all enemies in a small area around this agent", 

			PREDICTIVE_BRAWLING = "Predictive Brawling",
			PREDICTIVE_BRAWLING_TIP =  "Gain 3 AP",

			CHAMELEON_MOVEMENT = "Chameleon Movement",
			CHAMELEON_MOVEMENT_TIP = "Gain 3 AP.", 

			PIERCING_SCANNER = "Piercing Scanner",
			PIERCING_SCANNER_TIP = "Shots ignore 1 point of armor.", 

			PENETRATION_SCANNER = "Penetration Scanner",
			PENETRATION_SCANNER_TIP = "Melee weapons ignore 1 point of armor.", 
		},

		QUEST_MATERIAL = "Mysterious Material",
		QUEST_MATERIAL_TIP = "A block of mysterious material.",

		CLIP =  "Unregistered Ammunition",
		CLIP_TIP = "Refills a single weapon's clip. Rare ammunition that's evaded the government registration process.",
	
		DART_GUN1_NAME = "Neural Phaser",
		DART_GUN1_TOOLTIP = "Knocks a guard out from long range.",
	
		DART_GUN_DAM = "Hi-Velocity Dart Gun",

		DART_GUN_AMMO = "Police Dart Gun",
		
		TAGGER_GUN = "T.A.G. Pistol",
		TAGGER_GUN_TIP = "PWR operated pistol that tags a guard to show his patrol paths.",

	},


	THREATS = {
		PWR_REVERSAL_NODE = {
			WARNING = "PWR DRAIN\n-%d PWR",
		},
	},

	-- These are auto-generated by the UI tool.
	SCREENS = include( "strings_screens" )
}

return STRINGS
